services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: congeal-app
    image: congeal-app
    ports:
      - "3000:3000"
      - "25:25"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    environment:
      - POSTFIX_SERVER=${POSTFIX_SERVER}
      - POSTFIX_PORT=${POSTFIX_PORT}
      - POSTFIX_ACCOUNT=${POSTFIX_ACCOUNT}
      - POSTFIX_PASSWORD=${POSTFIX_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_REPLY_TO=${MAIL_REPLY_TO}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    restart: unless-stopped
    